#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting glpi domain)
path=$(sudo yunohost app setting glpi path)

sudo apt-get install php5-cli php5-gd php5-imap

# Copy files to the right place
final_path=/var/www/glpi
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Configure GLPI
mysql -u $db_user -p$db_pwd $db_user < ../conf/glpi.sql

# Install cron
if [ ! -f /etc/cron.d/glpi ];
then
	sudo cp ../conf/cron /etc/cron.d/glpi
fi

# Set permissions to glpi directory
sudo chown -R www-data: $final_path

# Remove install.php
sudo rm $final_path/install/install.php

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
sudo sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/glpi.conf

sudo sed -i "s@NAMETOCHANGE@glpi@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/glpi.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

# Reload Nginx and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app setting glpi skipped_uris -v "/plugins/fusioninventory"
sudo yunohost app ssowatconf

# update glpi databases
sudo su - wwww-data -c "php $final_path/install/update.php"

# update FusionInventory
sudo su - www-data -c "php /var/www/glpi/plugins/fusioninventory/scripts/cli_install.php"
